# -- Eva Twitch Chat Bot (Tbot) --
name: eva-tbot

networks:
  eva-net:
    external: true

secrets:
  twitch_credentials:
    file: /volume1/ros/secrets/credentials_bobassi.json

services:
  # -- TBOT: Twitch Interaction & Filtering --
  tbot:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.tbot
      args:
        - CACHE_BUST=${CACHE_BUST:-1}
    container_name: eva-tbot
    networks:
      - eva-net
    env_file:
      - ../.env
    environment:
      - TWITCH_CHAT_CHANNEL=bobassi
      # Passing the path to the Docker Secret
      - TWITCH_CHAT_CREDENTIALS=/run/secrets/twitch_credentials
    secrets:
      - twitch_credentials
    command: ros2 launch bob_launch generic.launch.py config:=/ros2_ws/src/bob_central/launch/tbot_launch.yaml
    volumes:
      - ../launch/tbot_launch.yaml:/ros2_ws/src/bob_central/launch/tbot_launch.yaml:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
