# -- Eva Twitch Chat Bot (Tbot) --
name: eva-tbot

networks:
  eva-net:
    external: true

secrets:
  twitch_credentials:
    file: /volume1/ros/secrets/credentials_bobassi.json

services:
  # -- TBOT: Twitch Interaction & Filtering --
  tbot:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.tbot
      args:
        - CACHE_BUST=${CACHE_BUST:-1}
    container_name: eva-tbot
    networks:
      - eva-net
    env_file:
      - ../.env
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - TWITCH_CHAT_CHANNEL=bobassi
      # Passing the path to the Docker Secret
      - TWITCH_CHAT_CREDENTIALS=/run/secrets/twitch_credentials
    secrets:
      - twitch_credentials
    volumes:
      - /blue/dev/tioros/ros2_ws/src/tioros:/ros2_ws/src/tioros
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
